[package]
name = "moose"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
limine = "0.2.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
