name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rust-src

    - name: Install NASM
      uses: ilammy/setup-nasm@v1

    - name: Build program1
      run: |
        cd program1
        cargo build --release --verbose

    - name: Build program2
      run: |
        cd program2
        cargo build --release --verbose

    - name: Build kernel
      run: |
        cd kernel
        cargo build --verbose

    - name: Test common
      run: |
        cd common
        cargo test

    - name: Test filesystem
      run: |
        cd fs
        cargo test
